### ISSUE TITLE
Unify the sidebar & main panel background colors

### ISSUE THREAD

**Issue by Bad3r** [orblazer/discord-nordic#21]
Thank you for bringing Nord to Discord.  
I personally prefer when both the main panel and sidebar use the same dark Nord background color. This matches other ports of Nord to other tools.

<table><tbody><tr><td>Discord-nordic</td><td>VSCode Nord theme</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/218303247-a40441e2-1c66-4e92-9616-4b66c3f9a36d.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/218303236-2191dcba-a5e4-43a6-9515-2045eacbfbb5.png"></figure></td></tr></tbody></table>

Logseq
![image](https://user-images.githubusercontent.com/25513724/218303835-a7093e25-be26-4bd8-a230-1771ae298b6c.png)
Discord-nordic
![](https://user-images.githubusercontent.com/25513724/218303247-a40441e2-1c66-4e92-9616-4b66c3f9a36d.png)
VSCode
![](https://user-images.githubusercontent.com/25513724/218303236-2191dcba-a5e4-43a6-9515-2045eacbfbb5.png)

**Comment by orblazer** [comment]
Hello,
Thanks for the issue. I'm not sure if that look great to have discord in this style.

If you want i have make an Proof Of Concept (and not finished) of that variant of theme.
![Screenshot_20230213_175057](https://user-images.githubusercontent.com/1344792/218521966-21c0ba3c-7690-4a44-aaee-2398c598cbf3.png)

You can put bellow code inside custom CSS or in theme file.
```css
:root {
    --background-primary: var(--nord-dark1);
    --background-secondary-alt: var(--nord-dark2);
    --background-tertiary: var(--nord-dark1);
    --background-message-hover: hsl(var(--primary-dark-500-hsl)/0.3);
    --channeltextarea-background: var(--background-secondary-alt);

    --scrollbar-thin-thumb: var(--primary-dark-500);
    --scrollbar-auto-thumb: var(--primary-dark-500);
    --scrollbar-auto-track: var(--primary-dark-700);
}

.scroller-3X7KbA,
.sidebar-1tnWFu,
.chatContent-3KubbW,
.sidebarRegion-1VBisG,
.sidebarRegionScroller-FXiQOh {
    border-right: 1px solid var(--background-secondary-alt);
}

.childWrapper-1j_1ub,
.circleIconButton-1VxDrg,
.accountProfileCard-lbN7n-,
.cardWrapper-1bSePP,
.cameraWrapper-nG8dpo,
.container-3EtAkD:not(:hover) .icon-2DGsye,
.backgroundContainer-gUNEZU,
.clickableContainer-3YtEIY,
.editCard-K9Q9mb,
.featureCard-3XHbjy,
.checklistHeader-3liG7E,
.header-Wl8ec-,
.enableContainer-H2cRts,
.welcomeChannel-_Q4qAA,
.descriptionInput-2-jF56,
.expandedFolderBackground-1kSAf6,
.wrapper-2SplAX,
.reaction-3vwAF2 {
    background-color: var(--background-secondary-alt);
}

.connection-YOVI9j,
.itemFilled-2Fo7lr,
.bd-addon-list .bd-addon-card,
.container-3EtAkD,
.tierBody-1d3UiS,
.container-AxP_J8,
.upsellContainer-2a5eMP,
.checklistContainer-12xGp5,
.container-13pE3E,
.previewContainer-29oeA6 {
    border: 1px solid var(--background-secondary-alt);
}

.embedFull-1HGV2S {
    background-color: var(--background-secondary-alt);
    border-left-color: var(--nord-dark4);
}

.notches-2w7UZJ.gray-3wP137 {
    color: var(--background-secondary) !important;   
}
.progress-1S-TDF {
    background-color: var(--primary-dark-500) !important;
}

.container-30qY7E {
    background-color: hsl(var(--primary-dark-500-hsl)/0.1) !important;
    border-color: var(--background-secondary-alt) !important;
}

.tierBody-1d3UiS,
.container-AxP_J8,
.previewContainer-29oeA6 {
    border-top: none;
}

.category-2OvQ93:hover,
.clickable-O5xo4T.container-2NdZr9:hover,
.folder-241Joy {
    background-color: var(--nord-dark3);
}

.fieldBackground-2TpuOY,
.container-AxP_J8 {
    background-color: var(--background-secondary);
}
```
