### ISSUE TITLE
[Feature Request] Flat Theme mode

### ISSUE THREAD

**Issue by Tetrax-10** [orblazer/discord-nordic#26]
## Can you make the theme look flat like this?

![Screenshot 2023-04-09 230920](https://user-images.githubusercontent.com/75513645/230788266-a161f645-b1d5-4869-8c89-41e4bede2608.png)

**CSS I used**
```css
.theme-dark {
    --background-primary: #2e3440 !important;
    --channeltextarea-background: #3b4252 !important;
    --background-secondary-alt: #2e3440 !important;
}

div[class*="winButton"] {
    margin-top: 4px !important;
}

div[class*="withFrame"] {
    background-color:#2e3440 !important;
    margin-top: 0 !important;
}
```
