### ISSUE TITLE
[BUG] Unifrom theme server list background color is different

### ISSUE THREAD

**Issue by diogotcorreia** [orblazer/discord-nordic#32]
**Describe the bug**
The background of the server list on the left side has a different background color in the channel list.

**To Reproduce**
_nothing_

**Expected behavior**
It should have the same background color as the other sections of the app.

**Screenshots**
![image](https://github.com/orblazer/discord-nordic/assets/7467891/4a5edeaa-621d-470f-a333-d119cd18944f)

**Versions (please complete the following information):**

- Theme style: Dark
- Theme version: 4.10.9
- Is `uniform` variant: Yes
- Discord Version: stable 279687 (16253d7) Host 0.0.45 x64 Linux 64-bit (6.7.10)
- Client name & version (BetterDiscord, Vencord, etc) : OpenAsar Unstable (2023)

**Additional context**
Thank you for the quick patch for the latest Discord version!

As per this problem, I've seemed to fix it myself by adding the following CSS:

```css
.wrapper__216eb {
    background-color: var(--background-primary);
    border-right: 1px solid var(--background-secondary-alt);
}
```

Relevant commit on my dotfiles: https://github.com/diogotcorreia/dotfiles/commit/6ddc383761850ac8d755a323050d7870b7ddfc37
