### ISSUE TITLE
Changing channel name font size?

### ISSUE THREAD

**Issue by Bad3r** [orblazer/discord-nordic#6]
Hi,
First, thank you for porting this awesome theme to Discord.
I wanted to add extra custom CSS to change the default font size for the channel name.
I was able to switch the font used in discord and the color of the channels with new messages using this custom.css
```css
 body, div, span, textarea, ::-webkit-input-placeholder {
    /**
    * Changing fonts.
    * Syntax: font-family: 'font name', fallbacks?, font type?;
    * Fallbacks are optional, font type is optional but helps the font render properly.
    * Example: font-family: 'Whitney', 'Arial', sans-serif;
    */
    font-family: 'Monolisa', 'Font Awesome 6 Pro', 'FontAwesome', sans-serif;
    }
    
    .hljs,
    .inline,
    .hljs :-webkit-any(ol, li, span),
    .editor-wrapper :-webkit-any(textarea, div, span) {
    /**
    * Keep Custom CSS editor and code related parts untouched.
    * Avoids issues when working with the Custom CSS editor.
    */
    font-family:  'Monolisa', 'Font Awesome 6 Pro', 'FontAwesome', 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
    }

.modeUnread-1qO3K1 .name-23GUGE {
  color: #ebcb8b;
  font-weight: 700;
}
```
The last section of the CSS file I found in your repo
```css
.modeUnread-1qO3K1 .name-23GUGE {
  color: #ebcb8b;
  font-weight: 700;
}
``` 
I wanted to make it easier for me to distinguish channels with new messages
![image](https://user-images.githubusercontent.com/25513724/144663578-62ca5db8-4e24-4273-9898-0fe075d5bc92.png)

Do you know how to change the font size for all channel names (active, new message, muted)?
